import { Country } from "./types";

export class LocationData {
  static readonly countriesList: Country[] = [
    { name: "Afghanistan", countryCode: "AF" },
    { name: "Albania", countryCode: "AL" },
    { name: "Argentina", countryCode: "America" },
    { name: "Australia", countryCode: "AU" },
    { name: "Brazil", countryCode: "America" },
    { name: "Canada", countryCode: "America" },
    { name: "China", countryCode: "CN" },
    { name: "Egypt", countryCode: "EG" },
    { name: "France", countryCode: "FR" },
    { name: "Germany", countryCode: "DE" },
    { name: "Greece", countryCode: "GR" },
    { name: "India", countryCode: "IN" },
    { name: "Indonesia", countryCode: "ID" },
    { name: "Italy", countryCode: "IT" },
    { name: "Japan", countryCode: "JP" },
    { name: "Kenya", countryCode: "KE" },
    { name: "Mexico", countryCode: "America" },
    { name: "Netherlands", countryCode: "NL" },
    { name: "New Zealand", countryCode: "NZ" },
    { name: "Nigeria", countryCode: "NG" },
    { name: "Norway", countryCode: "NO" },
    { name: "Pakistan", countryCode: "PK" },
    { name: "Peru", countryCode: "America" },
    { name: "Russia", countryCode: "RU" },
    { name: "Saudi Arabia", countryCode: "SA" },
    { name: "South Africa", countryCode: "ZA" },
    { name: "South Korea", countryCode: "KR" },
    { name: "Spain", countryCode: "ES" },
    { name: "Sweden", countryCode: "SE" },
    { name: "Switzerland", countryCode: "CH" },
    { name: "Thailand", countryCode: "TH" },
    { name: "Turkey", countryCode: "TR" },
    { name: "Ukraine", countryCode: "UA" },
    { name: "United Arab Emirates", countryCode: "AE" },
    { name: "United Kingdom", countryCode: "GB" },
    { name: "United States", countryCode: "America" },
    { name: "Venezuela", countryCode: "America" },
    { name: "Vietnam", countryCode: "VN" },
    { name: "Zimbabwe", countryCode: "ZW" },
  ];
}
