import { Country } from "./types";

export class LocationData {
  static readonly countriesList: Country[] = [
    { name: "Afghanistan", countryCode: "AF", continent: "Asia" },
    { name: "Albania", countryCode: "AL", continent: "Europe" },
    { name: "Argentina", countryCode: "AR", continent: "South America" },
    { name: "Australia", countryCode: "AU", continent: "Oceania" },
    { name: "Brazil", countryCode: "BR", continent: "South America" },
    { name: "Canada", countryCode: "CA", continent: "North America" },
    { name: "China", countryCode: "CN", continent: "Asia" },
    { name: "Egypt", countryCode: "EG", continent: "Africa" },
    { name: "France", countryCode: "FR", continent: "Europe" },
    { name: "Germany", countryCode: "DE", continent: "Europe" },
    { name: "Greece", countryCode: "GR", continent: "Europe" },
    { name: "India", countryCode: "IN", continent: "Asia" },
    { name: "Indonesia", countryCode: "ID", continent: "Asia" },
    { name: "Italy", countryCode: "IT", continent: "Europe" },
    { name: "Japan", countryCode: "JP", continent: "Asia" },
    { name: "Kenya", countryCode: "KE", continent: "Africa" },
    { name: "Mexico", countryCode: "MX", continent: "North America" },
    { name: "Netherlands", countryCode: "NL", continent: "Europe" },
    { name: "New Zealand", countryCode: "NZ", continent: "Oceania" },
    { name: "Nigeria", countryCode: "NG", continent: "Africa" },
    { name: "Norway", countryCode: "NO", continent: "Europe" },
    { name: "Pakistan", countryCode: "PK", continent: "Asia" },
    { name: "Peru", countryCode: "PE", continent: "South America" },
    { name: "Russia", countryCode: "RU", continent: "Asia" },
    { name: "Saudi Arabia", countryCode: "SA", continent: "Asia" },
    { name: "South Africa", countryCode: "ZA", continent: "Africa" },
    { name: "South Korea", countryCode: "KR", continent: "Asia" },
    { name: "Spain", countryCode: "ES", continent: "Europe" },
    { name: "Sweden", countryCode: "SE", continent: "Europe" },
    { name: "Switzerland", countryCode: "CH", continent: "Europe" },
    { name: "Thailand", countryCode: "TH", continent: "Asia" },
    { name: "Turkey", countryCode: "TR", continent: "Asia" },
    { name: "Ukraine", countryCode: "UA", continent: "Europe" },
    { name: "United Arab Emirates", countryCode: "AE", continent: "Asia" },
    { name: "United Kingdom", countryCode: "GB", continent: "Europe" },
    { name: "United States", countryCode: "US", continent: "North America" },
    { name: "Venezuela", countryCode: "VE", continent: "South America" },
    { name: "Vietnam", countryCode: "VN", continent: "Asia" },
    { name: "Zimbabwe", countryCode: "ZW", continent: "Africa" },
  ];
}
