name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Lint Code
      run: npm run lint

    - name: Run Tests
      run: npm run test
